### ISSUE TITLE
Implement transcript interaction record logging functionality on front end

### ISSUE THREAD

**Issue by joeldseidel** [NittanyAiAlliance/Admissions-Smart-OCR#34]
Collect log of changes made within a transcript. Get original output from the OCR, log of admin interactions with transcript, and final result.

**Comment by BikalpaN** [comment]
@joeldseidel please delete me from the email chains and unsubscribe.

**Comment by joeldseidel** [comment]
@BikalpaN To unsubscribe from the repo you must remove yourself as a watcher of the repo. I cannot remove watchers.
